### PR TITLE
Version 0.8.0

### PR DESCRIPTION
**Pull request by aviggiano**
# New features 🚢 
- Cloud (Not Render Farm) renders now open on a new, big window
- Desktop render upload has a more intuitive UI/UX
- Upload buttons (new version or new asset) are now easier to distinguish because of their distinct icons and size

# Bugfixes 🐛 
- Failed downloads are now cleaned up (2D/3D green progress bar/box) from the scene
- Assets without thumbnail now appear on the search results
- It is now possible to edit/reupload a scene that was uploaded through the API

# Other notable changes ✅ 
- Batch download now has only one button. It will restart from the beginning if the search query changes, and continue downloading sequentially otherwise
- Remove UI report (e.g. "Hana3D searching...") from the RHS of the screen (UI panel), leaving only the LHS of the screen (green/red text below the search results)
- Search will fetch 100 results instead of 20

# Known issues ❌
- Batch download can still cause a crash due to an unknown bug

### CODE REVIEW

**Review by impadalko — APPROVED** [review]

**Review by impadalko — APPROVED** [review]
Manda bala

**Review by h7seiji — APPROVED** [review]

**Comment by h7seiji** [comment]
Vamos fazer a release agora?
Que estamos tendo alguns problemas com o login na prod.
Eu mesmo não estou conseguindo fazer login, mas na dev eu consigo.

**Comment by aviggiano** [comment]
@h7seiji ia fazer assim que o slack voltasse 100%

nao tava ligado no problema do login -- sabe o que é?

**Comment by h7seiji** [comment]
Não consegui descobrir ainda, talvez por isso ter a release seria um fix mais rápido.

**Comment by aviggiano** [comment]
@h7seiji ok vou fazer

**Pull request merged**
